<?php
/**
*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
*
*1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
*
*By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

$sum = 0;
$overallsum = 0;
$i=1;
$j=2;

while($overallsum <= 4000000){
	if($i%2==0){
		$overallsum = $overallsum + $i;
	}

	if($j%2==0){
		$overallsum = $overallsum + $j;
	}
	
	$i=$j;
	$j=$sum;
}

echo "Sum of the even-valued terms :".$overallsum;

?>